server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  profiles:
    group:
      "local" : "local, jwt, oauth"
    active : local

---
spring:
  config:
    activate:
      on-profile: "local"

  datasource:
    url: jdbc:mysql://localhost:3306/social?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: rlagudals3
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true

    hibernate:
      ddl-auto: create