server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  profiles:
    group:
      "local" : "local, jwt, oauth"
    active : local

---
spring:
  config:
    activate:
      on-profile: "local"

  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/oauthtest4
    username: sa
    password:

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true

    hibernate:
      ddl-auto: create